[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wagtail_character_counter"
version = "26.9.1"
authors = [
  { name="Sebastvin", email="sebastian@kachange.eu" },
]

description = "A lightweight extension that enables character counting in Draftail editor."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django>=6.1.1",
    "wagtail>=8.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Sebastvin/wagtail-character-counter"
"Bug Tracker" = "https://github.com/Sebastvin/wagtail-character-counter/issues"